
# https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html
# CXX = g++
CXX = clang++
CPPFLAGS = -Wall -std=c++23 -pthread -g -O3
CPPFLAGS += -fvisibility=hidden -Bsymbolic  # https://www.youtube.com/watch?v=_enXuIxuNV4
# LDFLAGS =

# For profiling:
# CPPFLAGS += -pg
# LDFLAGS += -pg -g

LDLIBS = -lsfml-graphics -lsfml-window -lsfml-system
LDLIBS += $$(pkg-config absl_algorithm_container --libs)
LDLIBS += $$(pkg-config absl_flags --libs)
LDLIBS += $$(pkg-config absl_flags_parse --libs)
LDLIBS += $$(pkg-config absl_flat_hash_map --libs)
LDLIBS += $$(pkg-config absl_random_random --libs)
LDLIBS += $$(pkg-config absl_strings --libs)

all: minesweeper minesweeper-client

minesweeper: \
		agent_last.o \
		agent_random.o \
		agent_sfml.o \
		agent_websocket.o \
		env.o \
		kdtree.o \
		minesweeper.o \
		point.o
	$(CXX) $(LDFLAGS) -o $@ $^ $(LDLIBS)

minesweeper-client: \
		agent_sfml.o \
		minesweeper-client.o \
		point.o
	$(CXX) $(LDFLAGS) -o $@ $^ $(LDLIBS)

test: \
		catch_amalgamated.o \
		kdtree.o \
		kdtree_test.o \
		point.o
	$(CXX) $(LDFLAGS) -o $@ $^ $(LOADLIBES) $(LDLIBS)

run: all
	./minesweeper

run_test: test
	./test

clean:
	rm -f *.o \
		minesweeper \
		minesweeper-client \
		test

fresh: clean all

installdeps:
	sudo apt install build-essential clang libabsl-dev libboost-all-dev libsfml-dev libwebsocketpp-dev

gendeps:
	ls *.cc -1 | xargs -L 1 cpp -M -MM

############ everything below is generated by: make gendeps
agent_last.o: agent_last.cc agent_last.h agent.h minesweeper.h point.h \
 kdtree.h
agent_random.o: agent_random.cc agent_random.h agent.h minesweeper.h \
 point.h
agent_sfml.o: agent_sfml.cc agent_sfml.h agent.h minesweeper.h point.h
agent_websocket.o: agent_websocket.cc agent_websocket.h agent.h \
 minesweeper.h point.h
catch_amalgamated.o: catch_amalgamated.cc catch_amalgamated.h
env.o: env.cc env.h kdtree.h point.h minesweeper.h
kdtree.o: kdtree.cc kdtree.h point.h
kdtree_test.o: kdtree_test.cc catch_amalgamated.h kdtree.h point.h
minesweeper.o: minesweeper.cc agent.h minesweeper.h point.h agent_last.h \
 kdtree.h agent_random.h agent_sfml.h agent_websocket.h env.h
minesweeper-client.o: minesweeper-client.cc agent_sfml.h agent.h \
 minesweeper.h point.h
point.o: point.cc point.h
