name: C++ CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'master'
        submodules: recursive
    - name: deps
      run: make installdeps
    - name: make
      run: make
    - name: make test
      run: make test
    - name: test
      run: ./test
